numero = int(input("Digite um número: "))
print("loading...")
print('=' * 20)
print(f'{numero} * 0 = {numero * 0}')
print(f'{numero} * 1 = {numero * 1}')
print(f'{numero} * 2 = {numero * 2}')
print(f'{numero} * 3 = {numero * 3}')
print(f'{numero} * 4 = {numero * 4}')
print(f'{numero} * 5 = {numero * 5}')
print(f'{numero} * 6 = {numero * 6}')
print(f'{numero} * 7 = {numero * 7}')
print(f'{numero} * 8 = {numero * 8}')
print(f'{numero} * 9 = {numero * 9}')
print(f'{numero} * 10 = {numero * 10}')
print('=' * 20)